version: '3.11'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db

  ai_api:
    build: ./ai_api
    ports:
      - "8080:8080"
    env_file:
      - ai_api/.env

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: lani
      POSTGRES_PASSWORD: password
      POSTGRES_DB: promoease
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: